# 生产阶段
FROM alpine

# 设置工作目录为 /model-cache
WORKDIR /model-cache

# 复制构建阶段的文件到 /model-cache-original
COPY /model-cache-original /model-cache-original

# 启动逻辑
CMD ["/bin/sh", "-c", "if [ -z \"$(ls -A /model-cache)\" ]; then cp -r /model-cache-original/* /model-cache/; fi && tail -f /dev/null"]
