name: 构建 nllb-clip-large-siglip__v1 并推送 Docker 镜像

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: "33 5 * * 5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        remove-android: 'true'
        remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: 检出代码
      uses: actions/checkout@v2

    # 设置 Docker Buildx
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 登录到 cnb
    - name: 登录到 cnb
      run:
          docker login docker.cnb.cool -u cnb -p ${{ secrets.cnb }}

    # 登录到 Docker Hub、GHCR 或阿里云容器镜像
    - name: 登录到 Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 登录到 GitHub Container Registry (GHCR)
    - name: 登录到 GitHub 容器注册表 (GHCR)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    # 登录到阿里云容器镜像
    - name: 登录到阿里云容器镜像
      run:
          docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

    # 构建并推送多平台 Docker 镜像
    - name: 构建并推送多平台 Docker 镜像
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./nllb-clip-large-siglip__v1/Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          xkand/nllb-clip-large-siglip__v1:latest
          ghcr.io/tonc/nllb-clip-large-siglip__v1:latest
          registry.cn-hangzhou.aliyuncs.com/tonc/nllb-clip-large-siglip__v1:latest
          docker.cnb.cool/xkand/docker/nllb-clip-large-siglip__v1:latest
